package com.example.jeffnippard.model

interface TrainingProgram {
    fun setFBday1()
    fun setFBday2()
    fun setFBday3()
    fun setFBday4()
    fun setULday1()
    fun setULday2()
    fun setULday3()
    fun setULday4()
    fun setWeek1Day1()
    fun setWeek1Day2()
    fun setWeek1Day3()
    fun setWeek1Day4()
    fun setWeek2Day1()
    fun setWeek2Day2()
    fun setWeek2Day3()
    fun setWeek2Day4()
    fun setWeek3Day1()
    fun setWeek3Day2()
    fun setWeek3Day3()
    fun setWeek3Day4()
    fun setWeek4Day1()
    fun setWeek4Day2()
    fun setWeek4Day3()
    fun setWeek4Day4()
    fun setWeek5Day1()
    fun setWeek5Day2()
    fun setWeek5Day3()
    fun setWeek5Day4()
    fun setWeek6Day1()
    fun setWeek6Day2()
    fun setWeek6Day3()
    fun setWeek6Day4()
    fun setWeek7Day1()
    fun setWeek7Day2()
    fun setWeek7Day3()
    fun setWeek7Day4()
    fun setWeek8Day1()
    fun setWeek8Day2()
    fun setWeek8Day3()
    fun setWeek8Day4()
    fun setWeek9Day1()
    fun setWeek9Day2()
    fun setWeek9Day3()
    fun setWeek9Day4()
    fun setWeek10Day1()
    fun setWeek10Day2()
    fun setWeek10Day3()
    fun setWeek10Day4()
    fun setWeek11Day1()
    fun setWeek11Day2()
    fun setWeek11Day3()
    fun setWeek11Day4()
    fun setWeek12Day1()
    fun setWeek12Day2()
    fun setWeek12Day3()
    fun setWeek12Day4()




}